@startuml
right header
<font size=24 color=black><b>Registration
end header

actor User

User -> System: Pressed button(Registration)
System -> User: Offers registration form
User -> System: Fills in the fields: login, password, surname, name,\n e-mail, sphere of activity, level of awareness
User -> System: Confirms the correctness of the entered data
System -> System: Checks the entered data
System -> User: Sends an e-mail with confirmation link of registration
User -> System: Passing through the link in the e-mail
System -> User: Provides ass user rights

right footer
Questioning. Registration
NTUU "Igor Sikorsky Kyiv Polytechnic Institute"
Kyiv-2020
end footer
@enduml
