-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 22:45:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Survey
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Survey` ;

-- -----------------------------------------------------
-- Schema Survey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Survey` DEFAULT CHARACTER SET utf8 ;
USE `Survey` ;

-- -----------------------------------------------------
-- Table `Survey`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Survey`.`User` ;

CREATE TABLE IF NOT EXISTS `Survey`.`User` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `phoneNumber` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Survey`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Survey`.`Session` ;

CREATE TABLE IF NOT EXISTS `Survey`.`Session` (
  `idSession` INT NOT NULL,
  `start` DATE NOT NULL,
  `stop` DATE NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idSession`),
  UNIQUE INDEX `idSession_UNIQUE` (`idSession` ASC) VISIBLE,
  INDEX `fk_Session_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Session`
    FOREIGN KEY (`idUser`)
    REFERENCES `Survey`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Survey`.`Survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Survey`.`Survey` ;

CREATE TABLE IF NOT EXISTS `Survey`.`Survey` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Survey`.`SurveyState`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Survey`.`SurveyState` ;

CREATE TABLE IF NOT EXISTS `Survey`.`SurveyState` (
  `idSurveyState` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idSurveyState`),
  UNIQUE INDEX `idSurveyState_UNIQUE` (`idSurveyState` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Survey`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Survey`.`Event` ;

CREATE TABLE IF NOT EXISTS `Survey`.`Event` (
  `idEvent` INT NOT NULL,
  `date` DATE NOT NULL,
  `idSession` INT NOT NULL,
  `idSurveyState` INT NOT NULL,
  `idSurvey` INT NOT NULL,
  PRIMARY KEY (`idEvent`),
  INDEX `fk_Event_Session_idx` (`idSession` ASC) VISIBLE,
  INDEX `fk_Event_Survey_idx` (`idSurvey` ASC) VISIBLE,
  INDEX `fk_Event_SurveyState_idx` (`idSurveyState` ASC) VISIBLE,
  CONSTRAINT `fk_Event_Session`
    FOREIGN KEY (`idSession`)
    REFERENCES `Survey`.`Session` (`idSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Survey`
    FOREIGN KEY (`idSurvey`)
    REFERENCES `Survey`.`Survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_SurveyState`
    FOREIGN KEY (`idSurveyState`)
    REFERENCES `Survey`.`SurveyState` (`idSurveyState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Survey`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Survey`.`Role` ;

CREATE TABLE IF NOT EXISTS `Survey`.`Role` (
  `idRole` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idRole`),
  UNIQUE INDEX `idRole_UNIQUE` (`idRole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Survey`.`Grant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Survey`.`Grant` ;

CREATE TABLE IF NOT EXISTS `Survey`.`Grant` (
  `idGrant` INT NOT NULL,
  `idRole` INT NOT NULL,
  `idSurvey` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idGrant`),
  INDEX `fk_Grant_User_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_Grant_Survey_idx` (`idSurvey` ASC) VISIBLE,
  INDEX `fk_Grant__idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `fk_Grant_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `Survey`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grant_Survey`
    FOREIGN KEY (`idSurvey`)
    REFERENCES `Survey`.`Survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grant_Role`
    FOREIGN KEY (`idRole`)
    REFERENCES `Survey`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
