-- MySQL Script generated by MySQL Workbench
-- Wed Apr 29 19:21:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QuestioningForms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `QuestioningForms` ;

-- -----------------------------------------------------
-- Schema QuestioningForms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QuestioningForms` DEFAULT CHARACTER SET utf8 ;
USE `QuestioningForms` ;

-- -----------------------------------------------------
-- Table `QuestioningForms`.`UserType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`UserType` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`UserType` (
  `idUserType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(32) NOT NULL,
  `access` JSON NOT NULL,
  PRIMARY KEY (`idUserType`),
  UNIQUE INDEX `idUserType_UNIQUE` (`idUserType` ASC) VISIBLE,
  UNIQUE INDEX `Type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`User` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `surname` VARCHAR(64) NOT NULL,
  `age` INT NOT NULL,
  `phoneNumber` VARCHAR(32) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`idUser`, `email`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `Type_idx` (`type` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`type`)
    REFERENCES `QuestioningForms`.`UserType` (`idUserType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`Authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`Authentication` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`Authentication` (
  `email` VARCHAR(64) NOT NULL,
  `hash` VARCHAR(256) NOT NULL,
  `salt` VARCHAR(16) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `email_Auth`
    FOREIGN KEY (`email`)
    REFERENCES `QuestioningForms`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`QuestionFormType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`QuestionFormType` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`QuestionFormType` (
  `idFormType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(32) NOT NULL,
  `rule` JSON NOT NULL,
  PRIMARY KEY (`idFormType`),
  UNIQUE INDEX `Type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`QuestionForm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`QuestionForm` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`QuestionForm` (
  `idQuestionForm` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(64) NOT NULL,
  `typeQuestionForm` INT NOT NULL,
  PRIMARY KEY (`idQuestionForm`),
  UNIQUE INDEX `idQuestionForm_UNIQUE` (`idQuestionForm` ASC) VISIBLE,
  INDEX `author_idx` (`author` ASC) VISIBLE,
  INDEX `type_idx` (`typeQuestionForm` ASC) VISIBLE,
  CONSTRAINT `author_QF`
    FOREIGN KEY (`author`)
    REFERENCES `QuestioningForms`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_QF`
    FOREIGN KEY (`typeQuestionForm`)
    REFERENCES `QuestioningForms`.`QuestionFormType` (`idFormType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`QuestionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`QuestionType` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`QuestionType` (
  `idQuestionType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(32) NOT NULL,
  `rule` JSON NOT NULL,
  PRIMARY KEY (`idQuestionType`),
  UNIQUE INDEX `idQuestionType_UNIQUE` (`idQuestionType` ASC) VISIBLE,
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`Question` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `questionFormId` INT NOT NULL,
  `questionType` INT NOT NULL,
  `text` LONGTEXT NOT NULL,
  PRIMARY KEY (`idQuestion`),
  UNIQUE INDEX `idQuestion_UNIQUE` (`idQuestion` ASC) VISIBLE,
  INDEX `questionFormId_idx` (`questionFormId` ASC) VISIBLE,
  INDEX `questionType_idx` (`questionType` ASC) VISIBLE,
  CONSTRAINT `questionFormId_Q`
    FOREIGN KEY (`questionFormId`)
    REFERENCES `QuestioningForms`.`QuestionForm` (`idQuestionForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionType_Q`
    FOREIGN KEY (`questionType`)
    REFERENCES `QuestioningForms`.`QuestionType` (`idQuestionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`PossibleAnswer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`PossibleAnswer` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`PossibleAnswer` (
  `idPossibleAnswer` INT NOT NULL AUTO_INCREMENT,
  `questionId` INT NOT NULL,
  `author` VARCHAR(64) NOT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idPossibleAnswer`),
  UNIQUE INDEX `idPossibleAnswer_UNIQUE` (`idPossibleAnswer` ASC) VISIBLE,
  INDEX `questionId_idx` (`questionId` ASC) VISIBLE,
  INDEX `author_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `questionId_PA`
    FOREIGN KEY (`questionId`)
    REFERENCES `QuestioningForms`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `author_PA`
    FOREIGN KEY (`author`)
    REFERENCES `QuestioningForms`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`AnswerForm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`AnswerForm` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`AnswerForm` (
  `idAnswerForm` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(64) NULL DEFAULT NULL,
  `questionFormId` INT NOT NULL,
  PRIMARY KEY (`idAnswerForm`),
  UNIQUE INDEX `idAnswerForm_UNIQUE` (`idAnswerForm` ASC) VISIBLE,
  INDEX `author_idx` (`author` ASC) VISIBLE,
  INDEX `questionFormId_idx` (`questionFormId` ASC) VISIBLE,
  CONSTRAINT `author_AF`
    FOREIGN KEY (`author`)
    REFERENCES `QuestioningForms`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionFormId_AF`
    FOREIGN KEY (`questionFormId`)
    REFERENCES `QuestioningForms`.`QuestionForm` (`idQuestionForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuestioningForms`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuestioningForms`.`Answer` ;

CREATE TABLE IF NOT EXISTS `QuestioningForms`.`Answer` (
  `idAnswer` INT NOT NULL AUTO_INCREMENT,
  `answerFormId` INT NOT NULL,
  `possibleAnswerId` INT NULL DEFAULT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idAnswer`),
  UNIQUE INDEX `idAnswer_UNIQUE` (`idAnswer` ASC) VISIBLE,
  INDEX `answerFormId_idx` (`answerFormId` ASC) VISIBLE,
  INDEX `possibleAnswerId_idx` (`possibleAnswerId` ASC) VISIBLE,
  CONSTRAINT `answerFormId_A`
    FOREIGN KEY (`answerFormId`)
    REFERENCES `QuestioningForms`.`AnswerForm` (`idAnswerForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `possibleAnswerId_A`
    FOREIGN KEY (`possibleAnswerId`)
    REFERENCES `QuestioningForms`.`PossibleAnswer` (`idPossibleAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
